#!/bin/bash

PROJECT_URL=$(git remote get-url origin | sed -E 's/.+@(.+):(.+)\.git$/https:\/\/\1\/\2/')
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

open "$PROJECT_URL/merge_requests/new?merge_request%5Bsource_branch%5D=$BRANCH_NAME&merge_request%5Bforce_remove_source_branch%5D=true"
